MainApplication/PUCIT.AIMRL.TLS.MainApp/Controllers/PartialController.cs
using PUCIT.AIMRL.TLS.MainApp.Util;
using PUCIT.AIMRL.TLS.UI.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PUCIT.AIMRL.TLS.MainApp.Controllers
{
    public class PartialController : BaseController
    {
        public ActionResult YesNoModal()
        {
            return PartialView();
        }

    }
}

MainApplication/PUCIT.AIMRL.TLS.MainApp/Controllers/SecurityController.cs
using PUCIT.AIMRL.TLS.MainApp.Util;
using PUCIT.AIMRL.TLS.UI.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PUCIT.AIMRL.TLS.MainApp.Controllers
{
    public class SecurityController : BaseController
    {
        public ActionResult Index()
        {
            if (PUCIT.AIMRL.TLS.MainApp.Security.PermissionManager.perManageSecurityUsers == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return RedirectToAction("Permissions");
            }
        }

        //
        // GET: /Admin/
        public ActionResult Users()
        {
            if (PUCIT.AIMRL.TLS.MainApp.Security.PermissionManager.perManageSecurityUsers== false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                return View();
            }
        }
        public ActionResult Roles()
        {
            if (PUCIT.AIMRL.TLS.MainApp.Security.PermissionManager.perManageSecurityRoles == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Id = 1;
                return View();
            }
        }
        public ActionResult Permissions()
        {
            if (PUCIT.AIMRL.TLS.MainApp.Security.PermissionManager.perManageSecurityPermissions == false)
            {
                return RedirectToAction("Index", "Home");
            }
            else
            {
                ViewBag.Id = 2;
                return View();
            }
        }
    }
}

MainApplication/PUCIT.AIMRL.TLS.MainApp/Views/Security/Permissions.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.permissions.js")"></script>
}
@section scripts
{

    <script type="text/javascript">

        $(document).ready(function () {
            MyWebApp.UI.Permission.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/Permissions/")'>Permissions</a>
    </li>
}

<div class="page-content">
    <div class="page-header">
        <h1>
            Permissions

            <select style="display:inline ; font-size:small" id="selectType1">
                <option value="-1">All</option>
                <option value="1">Active</option>
                <option value="0">In Active</option>
            </select>
            <a role="button" class="btn-new-mail pull-right" data-toggle="modal" id="newpermission">
                <span class="btn btn-purple no-border">
                    <i class="menu-icon fa fa-pencil-square-o"></i>
                    <span class="bigger-110">Add new Permissions</span>
                </span>
            </a>
        </h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="Permissions">
                            <table id="simple-table2" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
        </div>
    </div><!-- PAGE CONTENT ENDS -->
</div>

@section PopupsAndTemplates
{

    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
    <div id="modal-form1" class="in" tabindex="-1" " style=" display:none;padding-right:17px">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="ModalClose1" class="close" data-dismiss="modal">×</button>
                    <h4 class="blue bigger">Permission information</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div style="padding-left:50px;">
                            <input type="hidden" name="hiddenidp" id="hiddenidp" />
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Name : </b></label>
                                <input type="text" class="input-sm form-control" id="permissionname" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Description : </b></label>
                                <input type="text" class="input-sm form-control" id="permissiondescription" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="CancelPer">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="Saveper">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>
    <script id="PermissionTemplate" type="text/x-handlebars-template">
        <thead>
            <tr id="#">
                <th class="center">#</th>
                <th>Name</th>
                <th>Description</th>
                <th scope="col" width="5%">
                    Edit
                </th>
                <th scope="col" width="5%">
                    Enable/Disable
                </th>
            </tr>
        </thead>
        <tbody>
            {{#each PermissionList}}
            <tr id="{{Id}}">
                <td>
                    {{Id}}
                </td>
                <td>
                    {{Name}}
                </td>
                <td>{{Description}}</td>
                <td align="center" align="middle">
                    <div class="tblActions">
                        <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEdit" title="Click to edit">
                            <i class="menu-icon fa fa-pencil-square-o"></i>
                            <span class="bigger-110"></span>
                        </a>
                    </div>
                </td>
                <td align="center" align="middle">
                    <div class="tblActions" isactive="{{IsActive}}">
                        {{#ifEqual IsActive false}}
                        <a href="#" class="btn btn-xs btn-round widget-color-green lnkDelete" title="Click to activate">
                            <i class="ace-icon icon-off"></i>
                        </a>
                        {{/ifEqual}}
                        {{#ifEqual IsActive true}}
                        <a href="#" class='delete btn btn-xs btn-danger btn-round lnkDelete' title="Click to deactivate">
                            <i class="ace-icon icon-off"></i>
                        </a>
                        {{/ifEqual }}
                    </div>
                </td>
            </tr>
            {{/each}}
        </tbody>
    </script>
}

MainApplication/PUCIT.AIMRL.TLS.MainApp/Views/Security/Roles.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.roles.js")"> </script>

}
@section scripts
{

    <script type="text/javascript">

        try { ace.settings.loadState('main-container') } catch (e) { }

        $(document).ready(function () {
            MyWebApp.UI.Role.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/Roles/")'>Roles</a>
    </li>
}

<div class="page-content">
    <div class="page-header">
        <h1>
            Roles
            <select style="display:inline ; font-size:small" id="selectType1">
                <option value="-1">All</option>
                <option value="1">Active</option>
                <option value="0">In Active</option>
            </select>
            <a role="button" class="btn-new-mail pull-right" data-toggle="modal" id="newrole">
                <span class="btn btn-purple no-border">
                    <i class="menu-icon fa fa-pencil-square-o"></i>
                    <span class="bigger-110">Add new Roles</span>
                </span>
            </a>
        </h1>
    </div><!-- /.page-header -->
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="Roles">
                            <table id="simple-table" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
        </div>
    </div><!-- PAGE CONTENT ENDS -->
</div>

@section PopupsAndTemplates
{
    <div id="modal-form" class=" in" tabindex="-1" style="display:none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="ModalClose" class="close" data-dismiss="modal">×</button>
                    <h4 class="blue bigger">Role information</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div style="padding-left:50px;">
                            <input type="hidden" name="hiddenid" id="hiddenid" />
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Name : </b></label>
                                <input type="text" class="input-sm form-control" id="rolename" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Description : </b></label>
                                <input type="text" class="input-sm form-control" id="roledescription" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="Cancel">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="Save">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div id="EditPermissionsModal" class="modal in" tabindex="-1" style="display: none; width:45%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="primary bigger">
                        Permissions Assignment
                        <button type="button" id="closeedit" class="close" data-dismiss="modal">×</button>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-11">
                            <div class="space-4"></div>
                            <div class="row">
                                <div id="draggable" style="max-height:250px;overflow-y:auto">
                                    <ol id="sortable1" style="list-style-type:none"></ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="CancelPermModal">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="SaveMappings">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>

    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
    <script id="RoleTemplate" type="text/x-handlebars-template">
    <thead>
        <tr id="#">
            <th>Name</th>
            <th>Description</th>
            <th scope="col" width="5%">Edit</th>
            <th scope="col" width="5%">Enable/Disable</th>
            <th scope="col" width="5%">Manage Permissions</th>
        </tr>
    </thead>
    <tbody>
        {{#each RoleList}}
        <tr id="{{Id}}">
            <td>
                <a href="#">{{Name}}</a>
            </td>
            <td>{{Description}}</td>
            <td align="center" align="middle">
                <div class="tblActions">
                    <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEdit" title="Click to edit">
                        <i class="menu-icon fa fa-pencil-square-o"></i>
                        <span class="bigger-110"></span>
                    </a>
                </div>
            </td>
            <td align="center" align="middle">
                <div class="tblActions">
                    {{#ifEqual IsActive false}}
                    <a href="#" class="btn btn-xs btn-round widget-color-green lnkDelete" title="Click to activate">
                        <i class="ace-icon icon-off"></i>
                    </a>
                    {{/ifEqual}}
                    {{#ifEqual IsActive true}}
                    <a href="#" class='delete btn btn-xs btn-danger btn-round lnkDelete' title="Click to deactivate">
                        <i class="ace-icon icon-off"></i>
                    </a>
                    {{/ifEqual }}
                </div>
            </td>
            <td align="center" align="middle">
                <div class="tblActions">
                    {{#ifEqual IsActive true }}
                    <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEditMapping" title="Click to edit" id="editMapping">
                        <i class="menu-icon fa fa-pencil-square-o "></i>
                        <span class="bigger-110"></span>
                    </a>
                    {{/ifEqual }}
                    {{#ifEqual IsActive false }}
                    <a href="#" class="btn btn-xs btn-round">
                        <i class="ace-icon icon-lock"></i>
                    </a>
                    {{/ifEqual }}
                </div>
            </td>
        </tr>
        {{/each}}
    </tbody>
</script>

    <script id="PermissionTemplate" type="text/x-handlebars-template">
        {{#each PermissionList}}
        <li class="dd-handle nondrag" id="{{Id}}">
            <input type="checkbox">
            {{Name}}
        </li>
        {{/each}}
    </script>
}

MainApplication/PUCIT.AIMRL.TLS.MainApp/Views/Security/Users.cshtml
@{
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
@section Header
{
    <script type="text/javascript" src="@Url.Content("~/Scripts/mywebapp/Security/mywebapp.ui.users.js")?s=@DateTime.UtcNow.Ticks"></script>
}
@section scripts
{
    <script type="text/javascript">
        $(document).ready(function () {
            MyWebApp.UI.User.readyMain();
        });
    </script>
}
@section BreadCrumb
{
    <li>
        <a href='@Url.Content("~/Security/")'>Security</a>
    </li>
    <li>
        <a href='@Url.Content("~/Security/Users/")'>Users</a>
    </li>
}


<div class="page-content">
    <div class="page-header">
        <div class="main-content">
            <div class="row">
                <div class="col-sm-12">
                    <div class="col-sm-6">
                        <label class="lbl">Name/Login/Email</label>
                        <input id="txtTextToSearch" type="text" class="input-sm form-control" placeholder="Type Name/Login/Email">
                    </div>
                    <div class="col-sm-2">
                        <label class="lbl">Active </label>
                        <select id="cmbIsActiveSearch" class="input-sm form-control">
                            <option selected value="-1">Any</option>
                            <option value="1">Yes</option>
                            <option value="0">No</option>
                        </select>
                    </div>
                    <div class="col-sm-2" style="padding-top:15px">
                        <a role="button" class="pull-right btn-new-mail" data-toggle="modal" id="search">
                            <span class="btn btn-purple no-border">
                                <i class="menu-icon fa fa-search"></i>
                                <span class="bigger-110">Search</span>
                            </span>
                        </a>
                    </div>
                    <div class="col-sm-2" style="padding-top:15px">
                        <a role="button" class="pull-right btn-new-mail" data-toggle="modal" id="newuser">
                            <span class="btn btn-purple no-border">
                                <i class="menu-icon fa fa-pencil-square-o"></i>
                                <span class="bigger-110">Add new User</span>
                            </span>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">

            <div class="row">
                <div class="col-sm-10">
                    <div class="col-sm-2">
                        Page Size: <select id="cmbPageSizeSearch">
                            <option value="5" selected>5</option>
                            <option value="10">10</option>
                            <option value="20">20</option>
                        </select>

                    </div>
                    <div class="col-sm-2">
                        <span id="spResultsFound"> </span>
                    </div>
                    <div class="col-sm-6">
                        <ul class="pagination pull-right no-margin"></ul>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <!-- PAGE CONTENT BEGINS -->
            <div class="row">
                <div class="col-xs-12">
                    <div class="message-list-container">
                        <div class="message-list" id="Users">
                            <table id="simple-table" class="table  table-bordered table-hover"></table>
                        </div>
                    </div>
                </div>
            </div><!-- /.row -->
        </div>
    </div><!-- /.page-header -->
</div>

@section PopupsAndTemplates
{
    <div id="modal-form" class=" in" tabindex="-1" style="display:none;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" id="ModalClose" class="close" data-dismiss="modal">×</button>
                    <h4 class="blue bigger">User information</h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div style="padding-left:50px;">
                            <input type="hidden" name="hiddenid" id="hiddenid" />
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Name : </b></label>
                                <input type="text" class="input-sm form-control" id="txtName" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Email : </b></label>
                                <input type="text" class="input-sm form-control" id="txtEmail" />
                            </div>
                        </div>
                        <div style="padding-left:50px;">
                            <div class="col-xs-5">
                                <label class="asterisk" for="form-field-first"><b>Login : </b></label>
                                <input type="text" class="input-sm form-control" id="txtLogin" />
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="Cancel">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="Save">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>

    <div id="EditRolesModal" class="modal in" tabindex="-1" style="display: none; width:45%;">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="primary bigger">
                        Roles Assignment
                        <button type="button" id="closeedit" class="close" data-dismiss="modal">×</button>
                    </h4>
                </div>
                <div class="modal-body">
                    <div class="row">
                        <div class="col-xs-12 col-sm-11">
                            <div class="space-4"></div>
                            <div class="row">
                                <div id="draggable" style="max-height:250px;overflow-y:auto">
                                    <ol id="sortable1" style="list-style-type:none"></ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-sm" data-dismiss="modal" id="CancelPermModal">
                        <i class="ace-icon fa fa-times"></i>
                        Cancel
                    </button>
                    <button class="btn btn-sm btn-primary" id="SaveMappings">
                        <i class="ace-icon fa fa-check"></i>
                        Save
                    </button>
                </div>
            </div>
        </div>
    </div>
    @{
        Html.RenderAction("YesNoModal", "Partial");
    }
    <script id="UserTemplate" type="text/x-handlebars-template">
    <thead>
        <tr id="#">
            <th>Name</th>
            <th>Description</th>
            <th scope="col" width="5%">Edit</th>
            <th scope="col" width="5%">Enable/Disable</th>
            <th scope="col" width="5%">Manage Roles</th>
        </tr>
    </thead>
    <tbody>
        {{#each UserList}}
        <tr id="{{UserId}}">
            <td>
                <a href="#">{{Name}}</a>
            </td>
            <td>{{Description}}</td>
            <td align="center" align="middle">
                <div class="tblActions">
                    <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEdit" title="Click to edit">
                        <i class="menu-icon fa fa-pencil-square-o"></i>
                        <span class="bigger-110"></span>
                    </a>
                </div>
            </td>
            <td align="center" align="middle">
                <div class="tblActions">
                    {{#ifEqual IsActive false}}
                    <a href="#" class="btn btn-xs btn-round widget-color-green lnkDelete" title="Click to activate">
                        <i class="ace-icon icon-off"></i>
                    </a>
                    {{/ifEqual}}
                    {{#ifEqual IsActive true}}
                    <a href="#" class='delete btn btn-xs btn-danger btn-round lnkDelete' title="Click to deactivate">
                        <i class="ace-icon icon-off"></i>
                    </a>
                    {{/ifEqual }}
                </div>
            </td>
            <td align="center" align="middle">
                <div class="tblActions">
                    {{#ifEqual IsActive true }}
                    <a role="button" data-toggle="modal" class="edit btn-xs btn-new-mail  btn btn-purple no-border lnkEditMapping" title="Click to edit" id="editMapping">
                        <i class="menu-icon fa fa-pencil-square-o "></i>
                        <span class="bigger-110"></span>
                    </a>
                    {{/ifEqual }}
                    {{#ifEqual IsActive false }}
                    <a href="#" class="btn btn-xs btn-round">
                        <i class="ace-icon icon-lock"></i>
                    </a>
                    {{/ifEqual }}
                </div>
            </td>
        </tr>
        {{/each}}
    </tbody>
</script>
    <script id="RoleTemplate" type="text/x-handlebars-template">
        {{#each RoleList}}
        <li class="dd-handle nondrag" id="{{Id}}">
            <input type="checkbox">
            {{Name}}
        </li>
        {{/each}}
    </script>
}